// data.mjs — fetch the public API once, normalize, cross-link. Build-time only.
// Reads only the API (no scrape dependency) so it can also run in CI for freshness.
import assert from 'node:assert';
import { fileURLToPath } from 'node:url';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { resolveQmiHero } from './resolve-qmi-hero.mjs';
const API = process.env.ESP_API || 'https://esperanza-api.round-base-ed8c.workers.dev/api/public';

const un = v => (Array.isArray(v) ? v[0] : v);
// Normalize R2 image URLs to the CDN host AND serve raster images through Cloudflare's
// image transform (format=auto → webp/avif, quality + width cap). This cuts page weight
// ~10x (a 1.5 MB hero → ~150 KB) with no visible quality loss. Skips PDFs/SVGs and
// already-transformed URLs. Transformations are enabled on the hazardhouse.ai zone.
const IMG_TX = 'format=auto,quality=82,width=1600';
const fixHost = u => {
  if (!u) return u;
  let s = String(u).replace(/^https:\/\/<R2_PUBLIC_BUCKET>\.r2\.dev/, 'https://img.hazardhouse.ai');
  if (/^https:\/\/img\.hazardhouse\.ai\//.test(s) && !s.includes('/cdn-cgi/image/') && /\.(jpe?g|png|webp|avif)(\?|$)/i.test(s)) {
    s = s.replace('https://img.hazardhouse.ai/', `https://img.hazardhouse.ai/cdn-cgi/image/${IMG_TX}/`);
  }
  return s;
};
export const slugify = s => String(s || '').toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// Ascending price comparator, missing/zero prices LAST — a "TBD"/no-price card must
// never masquerade as the cheapest. `get` returns the price to sort on.
export const byPriceAsc = get => (a, b) => {
  const pa = Number(get(a)) > 0 ? Number(get(a)) : Infinity;
  const pb = Number(get(b)) > 0 ? Number(get(b)) : Infinity;
  return pa === pb ? 0 : pa - pb;
};

// Interim bridge: floor-plan slug -> _FP.png drawing (already in R2). Used only until
// floor_plans.floor_plan_image is backfilled in D1 (then the API field wins). Remove
// this file + the FP_MAP fallback below once R1 is populated. See handoff context doc.
const FP_MAP = (() => { try { const p = join(import.meta.dirname, 'fp-image-map.json'); return existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : {}; } catch { return {}; } })();

// Per-home media harvested from the original O'Neill QMI pages (hero elevation
// render, full photo set, inline plan drawings) — D1's image_url/photo_gallery is
// incomplete/wrong for many homes. Generated by harvest-qmi-media.mjs.
const QMI_MEDIA = (() => { try { const p = join(import.meta.dirname, 'assets', 'qmi-media-map.json'); return existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : {}; } catch { return {}; } })();

async function getJSON(path) {
  const r = await fetch(API + path);
  if (!r.ok) throw new Error(`${path} -> ${r.status}`);
  return r.json();
}

function normQmi(h) {
  const f = h.fields || h;
  const fp = un(f['FP: Image']);
  let gallery = [];
  const g = f.photo_gallery; // exposed by the esperanza-cf PR (Task 13); absent until then
  if (Array.isArray(g)) gallery = g.map(x => ({ url: fixHost(x.url || x), alt: x.alt || '' }));
  const hn = f.housenumber != null ? String(f.housenumber).trim() : '';
  const lot = hn || undefined; // raw — the original shows "Lot #007", zeros intact
  return {
    id: h.id, price: f.Price,
    beds: f.bedroom_count, baths: f.bathroom_count, halfBaths: f.half_bathroom_count,
    stories: f.stories != null ? f.stories : f.stories_count, garage: un(f['FP: Garage']),
    lot, hersScore: f.hers_score,
    livingSqft: f.living_square_footage, totalSqft: f.total_square_footage,
    community: f.Community, communityId: un(f['Community (Link)']),
    floorPlan: f['Floor Plan'], floorPlanId: un(f['Floor Plan (Link)']),
    collection: un(f['FP: Collection']),
    slug: f.slug, city: f.City, postalCode: f.postal_code, address: f.address,
    image: fixHost(f.image_url), gallery,
    fpImage: fp ? fixHost(fp.url || fp) : null, fpDescription: f['FP: Description'],
    planViewerUrl: un(f['FP: Plan Viewer']), virtualTourUrl: un(f['FP: Virtual Tour']),
    elevation: f.elevation,
    availability: f.availability_text, availableNow: f['Available Now'], moveInDate: f['Move-In Date'],
    description: f.Description, promo: f.promo_text, promoStyle: f.promo_banner_style,
    // Phase 1 additive contract. `promotionId` is IDENTITY and is never gated: the
    // backend's show_card_badge / show_card_cta flags empty the copy fields only, so a
    // home with both surfaces off still declares which offer it won (that attribute is
    // what the offer page's probes and the card-level links key on). `cardBadge` and the
    // CTA pair are independent surfaces — empty means render nothing AND strip whatever
    // the June-8 harvest baked there, never fall back to the old copy. Named `cardBadge`
    // rather than `badge` because `badge` is already the harvest's {text,color} object in
    // sections.mjs (harvestBadge), and two different shapes under one name is a trap.
    promotionId: un(f.promotion_id), cardBadge: f.card_badge_text,
    promoCtaLabel: f.promo_cta_label, promoCtaLink: f.promo_cta_link,
    selfTourAvailable: !!f.self_tour_available, nterNow: f.nter_now || null,
    pdfUrl: f['Dynamic PDF'],
    lat: f.latitude != null ? Number(f.latitude) : (f.geo_latitude != null ? Number(f.geo_latitude) : null),
    lng: f.longitude != null ? Number(f.longitude) : (f.geo_longitude != null ? Number(f.geo_longitude) : null),
  };
}

function normCommunity(c) {
  const p = c.coordinates ? String(c.coordinates).split(',') : [];
  return {
    // Re-slugify: D1 slugs can carry literal punctuation ("retama-village-(55-)-...");
    // live URLs (and the scrape's own page tree) use the clean form.
    id: c.id, name: c.name, slug: c.slug && slugify(c.slug), city: c.town,
    lat: p[0] != null && p[0] !== '' ? Number(p[0]) : null,
    lng: p[1] != null && p[1] !== '' ? Number(p[1]) : null,
    address: c.address, image: fixHost(c.image), secondaryImage: fixHost(c.secondaryImage),
    // Full community photo gallery (communities.photo_gallery_json → API photoGallery),
    // host-fixed to img.hazardhouse.ai; empty when a community has no gallery (render
    // falls back to hero+secondary). Mirrors normQmi's gallery handling.
    photoGallery: Array.isArray(c.photoGallery) ? c.photoGallery.map(g => ({ url: fixHost(g && g.url != null ? g.url : g), alt: (g && g.alt) || c.name })) : [],
    priceFrom: c.priceFrom, comingSoon: !!c.comingSoon, sqft: c.sqft, beds: c.beds, baths: c.baths,
    description: c.description, amenities: c.amenities, promo: c.promoBannerText,
    // Phase 1 additive contract, camelCase for location records. Identity is ungated;
    // the copy fields arrive already gated by show_card_badge / show_card_cta.
    promotionId: c.promotionId, cardBadge: c.promoBadgeText,
    promoStyle: c.promoBannerStyle, promoCtaLabel: c.promoCtaLabel, promoCtaLink: c.promoCtaLink,
    officePhone: c.officePhone, officeHours: c.officeHours, scheduleVisit: c.scheduleVisit,
    // HOA documents (CCRs, amendments) — [{title, link}], link is an R2 PDF url.
    hoaLinks: Array.isArray(c.hoaLinks) ? c.hoaLinks.filter((l) => l && l.link) : [],
  };
}

// City landing pages (/{slug}/): only the hero copy is CMS-editable today.
function normCity(c) {
  return { id: c.id, name: c.name, slug: c.slug, heroDescription: c.heroDescription };
}

function normFloorplan(fp) {
  return {
    id: fp.id, name: fp.name, slug: fp.slug, collection: fp.collection,
    startingPrice: fp.startingPrice, communityPrices: fp.communityPrices || {},
    bedroomMin: fp.bedroomMin, bedroomMax: fp.bedroomMax, bathroomMin: fp.bathroomMin, bathroomMax: fp.bathroomMax,
    garage: fp.carGarageCount, stories: fp.storiesCount,
    livingSqft: fp.livingSquareFootage, totalSqft: fp.totalSquareFootage,
    masterBed: fp.masterBedLocation, hersScore: fp.hersScore, communities: fp.communities,
    image: fixHost(fp.image), description: fp.description, floorPlanImage: fixHost(fp.floorPlanImage),
    planViewerUrl: fp.planViewerUrl, virtualTourUrl: fp.virtualTourUrl, brochurePdfUrl: fp.brochurePdfUrl,
    promo: fp.promoBannerText,
    // Plan caveat 1: the floor-plan payload already carried both strings, but this mapping
    // retained only promoBannerText, so the gated badge and CTA could never reach a card.
    promotionId: fp.promotionId, cardBadge: fp.promoBadgeText,
    promoStyle: fp.promoBannerStyle, promoCtaLabel: fp.promoCtaLabel, promoCtaLink: fp.promoCtaLink,
  };
}

export async function loadData() {
  // /promotions and /cities are non-fatal: promotions only feeds the "is this baked
  // promo copy still live?" gate (promo-utils.livePromoTexts), which fails open on an
  // empty list; cities only feeds the city-hero copy bake, which skips absent cities
  // (the page keeps its committed copy — same freeze as before the bake existed).
  const [q, c, f, s, pr, ct] = await Promise.all([
    getJSON('/qmi'), getJSON('/communities'), getJSON('/floorplans'), getJSON('/settings').catch(() => ({})),
    getJSON('/promotions').catch(() => ({})),
    getJSON('/cities').catch(() => ({})),
  ]);
  const promotions = pr.promotions || [];
  const cities = (ct.cities || []).map(normCity);
  const qmis = (q.homes || []).map(normQmi);
  const communities = (c.communities || []).map(normCommunity);
  const fpRaw = f.floorplans || f.floor_plans || (Array.isArray(f) ? f : []);
  const floorplans = fpRaw.map(normFloorplan);
  if (!qmis.length || !communities.length || !floorplans.length) {
    throw new Error(`empty API payload: qmi=${qmis.length} comm=${communities.length} fp=${floorplans.length} — refusing to build`);
  }
  const commById = new Map(communities.map(x => [x.id, x]));
  const commByName = new Map(communities.map(x => [String(x.name).toLowerCase(), x]));
  const fpById = new Map(floorplans.map(x => [x.id, x]));
  for (const h of qmis) {
    h.communityObj = commById.get(h.communityId) || null;
    h.floorplanObj = fpById.get(h.floorPlanId) || null;
    // plan-first stories: D1 per-home stories_count is missing/wrong for many homes
    if (h.floorplanObj && h.floorplanObj.stories != null) h.stories = h.floorplanObj.stories;
    // Harvested media is a fallback only — admin photo_gallery + image_url are the source
    // of truth for card/detail heroes once the panel has real uploads.
    const qm = (QMI_MEDIA.homes || {})[h.slug || slugify(h.address)];
    if (qm && !h.gallery.length) {
      if (qm.photos?.length) h.gallery = qm.photos.map(u => ({ url: fixHost(u), alt: h.address }));
      else if (qm.source === 'live') h.gallery = [];
    }
    h.image = resolveQmiHero({ image: h.image }, qm, fixHost);
    // Floor-plan drawing, HOME-specific first (mirrors the PDF worker's precedence:
    // qmi.floor_plan_image admin override, THEN the plan's floor_plan_image). The
    // public /qmi API doesn't expose the per-home override column yet, so the
    // original page's own harvested viewer drawing is our home-specific source; the
    // plan-level R1 field must not outrank it (it's the "default plan image" bug —
    // 2310 Emory Trail's custom Bahia drawing). Then the harvested per-plan pool,
    // then the committed _FP.png map (interim). When none exist, live O'Neill embeds
    // the home hero in the iviewer (not the FP elevation art).
    const fpSlug = (h.floorplanObj && h.floorplanObj.slug) || slugify(h.floorPlan);
    h.planImage = fixHost((qm && qm.planImages && qm.planImages[0])
      || (h.floorplanObj && h.floorplanObj.floorPlanImage)
      || ((QMI_MEDIA.plans || {})[fpSlug] || [])[0]
      || FP_MAP[fpSlug]
      || h.fpImage
      || null);
    // Galleryless homes (e.g. under construction): fall back to the community's model
    // photos (already in R2) until real photo_gallery_json lands in D1 — but not when
    // a live harvest explicitly found no gallery photos for this home.
    const liveGalleryEmpty = qm && qm.source === 'live' && Array.isArray(qm.photos) && !qm.photos.length;
    if (!h.gallery.length && h.communityObj && !liveGalleryEmpty) {
      h.gallery = [h.communityObj.image, h.communityObj.secondaryImage].filter(Boolean).map(u => ({ url: fixHost(u), alt: h.community }));
    }
  }
  for (const cm of communities) {
    // Order low->high by the SAME price each card renders on the community page:
    // QMI card shows h.price, plan card (planCardHtml) shows fp.startingPrice.
    cm.homes = qmis.filter(h => h.communityId === cm.id).sort(byPriceAsc(h => h.price));
    cm.plans = floorplans
      // Lineup = the admin "Floor Plans Offered" picker ONLY (fp.communities CSV). The
      // cep-price OR-clause was dropped: a 32-community scan found every cep-priced pair
      // is already in the CSV (cep-only = 0), so this hides no real plan, and it stops a
      // plan appearing on a community page purely because Snowflake priced it there —
      // matching the backend "picker is the sole lineup source" change (parity 2026-07-21).
      .filter(fp => String(fp.communities || '').toLowerCase().includes(String(cm.name).toLowerCase()))
      .sort(byPriceAsc(fp => fp.startingPrice));
  }
  for (const fp of floorplans) {
    fp.homes = qmis.filter(h => h.floorPlanId === fp.id).sort(byPriceAsc(h => h.price));
    fp.communityList = Object.keys(fp.communityPrices).map(n => commByName.get(n.toLowerCase())).filter(Boolean);
  }
  return { qmis, communities, floorplans, promotions, cities, settings: s, commById, commByName, fpById };
}

async function demo() {
  const d = await loadData();
  assert(d.qmis.length > 50, 'qmis loaded');
  assert(d.communities.length > 10, 'communities loaded');
  assert(d.floorplans.length > 20, 'floorplans loaded');
  assert(Array.isArray(d.promotions), 'promotions is always an array (non-fatal fetch)');
  const withComm = d.qmis.find(h => h.communityObj);
  assert(withComm, 'at least one QMI cross-links to a community');
  const withStories = d.qmis.find(h => h.stories != null);
  assert(withStories, 'at least one QMI has stories');
  const withLot = d.qmis.find(h => h.lot != null);
  assert(withLot, 'at least one QMI has a lot number');
  const withHers = d.qmis.find(h => h.hersScore != null);
  assert(withHers, 'at least one QMI has a HERS score');
  const withPlans = d.communities.find(c => c.plans.length);
  assert(withPlans, 'at least one community cross-links to floor plans');
  // Price low->high (missing prices last) on community-page plan + QMI lists.
  const asc = (arr, get) => {
    let seenNoPrice = false;
    for (const x of arr) {
      const p = Number(get(x));
      if (!(p > 0)) { seenNoPrice = true; continue; }
      assert(!seenNoPrice, 'priced item after a no-price item — not low->high with nulls last');
    }
    let prev = 0;
    for (const x of arr) { const p = Number(get(x)); if (p > 0) { assert(p >= prev, 'community list not ascending by price'); prev = p; } }
  };
  const cP = d.communities.find(c => c.plans.length > 1) || withPlans;
  asc(cP.plans, fp => fp.startingPrice);
  const cH = d.communities.find(c => c.homes.length > 1);
  if (cH) asc(cH.homes, h => h.price);
  const fpH = d.floorplans.find(fp => fp.homes.length > 1);
  if (fpH) asc(fpH.homes, h => h.price);
  assert(byPriceAsc(x => x.p)({ p: null }, { p: 100 }) > 0, 'byPriceAsc: null sorts after a price');
  assert(byPriceAsc(x => x.p)({ p: 100 }, { p: 200 }) < 0, 'byPriceAsc: lower price first');
  assert(typeof slugify('El Edén!') === 'string' && slugify('El Eden') === 'el-eden', 'slugify');
  const aq14924 = d.qmis.find(h => h.slug === '14924-aqualina-way');
  assert(aq14924 && aq14924.planImage && aq14924.planViewerUrl && !Array.isArray(aq14924.planViewerUrl),
    '14924-aqualina-way resolves planImage + scalar planViewerUrl');
  assert(aq14924.planImage.includes('AQ109'),
    '14924-aqualina-way plan viewer uses harvested floor-plan drawing (live parity)');
  assert(aq14924.planImage !== aq14924.image,
    '14924-aqualina-way plan viewer must not reuse admin hero photo');
  console.log('data.mjs demo() passed:', d.qmis.length, 'qmi', d.communities.length, 'comm', d.floorplans.length, 'fp');
}
if (process.argv.includes('--check') && process.argv[1] === fileURLToPath(import.meta.url)) demo();
