// test-dom.mjs — a minimal DOM for island fixtures. Node-only; never shipped or imported
// by the worker or the browser.
//
// WHY THIS EXISTS: the promotion islands' contract is what they do to the DOM — fill a
// hook, and REMOVE stale baked markup when a value is gated off. Asserting a helper's
// return value cannot see a removal, so the fixtures have to run the real browser branch
// against a real tree. This repo has no dependencies at all (no node_modules, no jsdom),
// and adding one to a Cloudflare-Workers site to test 200 lines of DOM code is a worse
// trade than 300 lines of shim.
//
// SCOPE, AND WHY IT IS SAFE: this parses ONLY markup this repo generates — the offer
// region from offer-shell.mjs and the card fragments the islands build. It is not a
// general HTML parser and must not be pointed at the 147KB scrape chrome. `assertParses()`
// pins that honesty: every fixture round-trips to its own input bytes, so a construct the
// parser mishandles fails the fixture instead of silently testing a wrong tree.

const VOID = new Set(['area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'param', 'source', 'track', 'wbr']);
const RAW = new Set(['script', 'style', 'textarea']);
// Attributes that render as bare names (`hidden`), not `name=""` — the offer shell emits
// `hidden` exactly this way, so serialization has to match or round-trip fails.
const BOOLEAN_ATTRS = new Set(['hidden', 'disabled', 'checked', 'selected', 'readonly', 'multiple', 'required', 'novalidate', 'autofocus', 'defer', 'async']);

// Attribute serialization mirrors offer-shell.mjs `esc()` (`&<>"`) rather than the HTML
// spec's minimal set (`&"`). The markup under test is generated BY that esc(), so matching
// it is what lets assertParses() demand byte-exact round-trips; the spec's minimal form
// would turn a generated `&gt;` back into a bare `>` and fail every fidelity check.
const escAttr = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const unescape = s => String(s).replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&nbsp;/g, '\u00a0').replace(/&amp;/g, '&');
const escText = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

class Node {
  constructor(type) { this.nodeType = type; this.parentNode = null; }
  get parentElement() { return this.parentNode && this.parentNode.nodeType === 1 ? this.parentNode : null; }
  // The live-refresh islands INSERT a surface a stale page baked without, and the only
  // honest place to put one is next to the node it belongs beside — so they need
  // `insertBefore(node, ref.nextSibling)`, the standard "insert after" idiom.
  get nextSibling() {
    if (!this.parentNode) return null;
    const i = this.parentNode.childNodes.indexOf(this);
    return i === -1 ? null : (this.parentNode.childNodes[i + 1] || null);
  }
  remove() {
    if (!this.parentNode) return;
    const i = this.parentNode.childNodes.indexOf(this);
    if (i !== -1) this.parentNode.childNodes.splice(i, 1);
    this.parentNode = null;
  }
}

class TextNode extends Node {
  constructor(text) { super(3); this.data = text; }
  get textContent() { return this.data; }
  get outerHTML() { return escText(this.data); }
}

class CommentNode extends Node {
  constructor(data) { super(8); this.data = data; }
  get textContent() { return ''; }
  get outerHTML() { return '<!--' + this.data + '-->'; }
}

class ClassList {
  constructor(el) { this.el = el; }
  _list() { return String(this.el.getAttribute('class') || '').split(/\s+/).filter(Boolean); }
  _write(list) { this.el.setAttribute('class', list.join(' ')); }
  contains(c) { return this._list().includes(c); }
  add(...cs) { const l = this._list(); for (const c of cs) if (!l.includes(c)) l.push(c); this._write(l); }
  remove(...cs) { this._write(this._list().filter(c => !cs.includes(c))); }
  toggle(c, on) { if (on === undefined ? this.contains(c) : !on) this.remove(c); else this.add(c); }
}

// `el.style.top = '2.5rem'` (incentive-live.js offsets the availability banner) has to
// reach the serialized attribute, or a fixture cannot see the change.
function styleProxy(el) {
  const read = () => {
    const out = new Map();
    for (const part of String(el.getAttribute('style') || '').split(';')) {
      const i = part.indexOf(':');
      if (i > 0) out.set(part.slice(0, i).trim(), part.slice(i + 1).trim());
    }
    return out;
  };
  const write = map => {
    const s = [...map].filter(([, v]) => v !== '').map(([k, v]) => `${k}:${v}`).join(';');
    if (s) el.setAttribute('style', s); else el.removeAttribute('style');
  };
  const dash = k => k.replace(/[A-Z]/g, m => '-' + m.toLowerCase());
  return new Proxy({}, {
    get(_, k) {
      if (k === 'setProperty') return (n, v) => { const m = read(); m.set(n, v); write(m); };
      if (k === 'removeProperty') return n => { const m = read(); m.delete(n); write(m); };
      return read().get(dash(String(k))) || '';
    },
    set(_, k, v) { const m = read(); const n = dash(String(k)); if (v === '' || v == null) m.delete(n); else m.set(n, String(v)); write(m); return true; },
  });
}

class Element extends Node {
  constructor(tagName) {
    super(1);
    this.tagName = String(tagName).toUpperCase();
    this.localName = String(tagName).toLowerCase();
    this.attrs = new Map();
    this.childNodes = [];
    this.classList = new ClassList(this);
    this.style = styleProxy(this);
  }
  get children() { return this.childNodes.filter(n => n.nodeType === 1); }
  get firstChild() { return this.childNodes[0] || null; }
  get id() { return this.getAttribute('id') || ''; }
  get className() { return this.getAttribute('class') || ''; }
  set className(v) { this.setAttribute('class', v); }
  // `hidden` is the offer shell's own gating mechanism, so the property and the attribute
  // must be the same fact — an island that sets `el.hidden = false` has to make the
  // serialized attribute disappear.
  get hidden() { return this.hasAttribute('hidden'); }
  set hidden(v) { if (v) this.setAttribute('hidden', ''); else this.removeAttribute('hidden'); }
  getAttribute(n) { const v = this.attrs.get(String(n).toLowerCase()); return v === undefined ? null : v; }
  setAttribute(n, v) { this.attrs.set(String(n).toLowerCase(), String(v)); }
  removeAttribute(n) { this.attrs.delete(String(n).toLowerCase()); }
  hasAttribute(n) { return this.attrs.has(String(n).toLowerCase()); }
  appendChild(node) { node.remove(); node.parentNode = this; this.childNodes.push(node); return node; }
  insertBefore(node, ref) {
    node.remove();
    const i = ref ? this.childNodes.indexOf(ref) : -1;
    node.parentNode = this;
    if (i === -1) this.childNodes.push(node); else this.childNodes.splice(i, 0, node);
    return node;
  }
  removeChild(node) { node.remove(); return node; }
  replaceChildren(...nodes) { for (const c of this.childNodes.slice()) c.remove(); for (const n of nodes) this.appendChild(n); }
  cloneNode(deep) {
    const el = new Element(this.localName);
    for (const [k, v] of this.attrs) el.attrs.set(k, v);
    if (deep) for (const c of this.childNodes) el.appendChild(c.nodeType === 1 ? c.cloneNode(true) : c.nodeType === 3 ? new TextNode(c.data) : new CommentNode(c.data));
    return el;
  }
  get textContent() { return this.childNodes.map(n => n.textContent).join(''); }
  set textContent(v) { this.childNodes.length = 0; if (v !== '') this.appendChild(new TextNode(String(v))); }
  get innerHTML() { return this.childNodes.map(n => n.outerHTML).join(''); }
  set innerHTML(html) {
    for (const c of this.childNodes.slice()) c.remove();
    for (const n of parseFragment(String(html), this.localName)) this.appendChild(n);
  }
  get outerHTML() {
    const attrs = [...this.attrs].map(([k, v]) => (v === '' && BOOLEAN_ATTRS.has(k) ? ' ' + k : ` ${k}="${escAttr(v)}"`)).join('');
    if (VOID.has(this.localName)) return `<${this.localName}${attrs}>`;
    const inner = RAW.has(this.localName) ? this.childNodes.map(n => (n.nodeType === 3 ? n.data : n.outerHTML)).join('') : this.innerHTML;
    return `<${this.localName}${attrs}>${inner}</${this.localName}>`;
  }
  matches(sel) { return matchesAny(this, sel); }
  closest(sel) { let n = this; while (n && n.nodeType === 1) { if (n.matches(sel)) return n; n = n.parentNode; } return null; }
  querySelector(sel) { return this.querySelectorAll(sel)[0] || null; }
  querySelectorAll(sel) {
    const out = [];
    const walk = el => {
      for (const c of el.children) {
        if (matchesAny(c, sel)) out.push(c);
        walk(c);
      }
    };
    walk(this);
    return out;
  }
}

// ── selectors ────────────────────────────────────────────────────────────────
// Supported: comma lists, descendant combinators, and compound simple selectors made of
// tag / #id / .class / [attr] / [attr="v"] / [attr*="v"] / :not(<simple>). Anything else
// THROWS rather than quietly matching nothing — a fixture must never pass because its
// selector was silently unsupported.
const SIMPLE_RE = /^(?:[a-zA-Z][\w-]*|#[\w-]+|\.[\w-]+|\[[\w-]+(?:[*^$]?=(?:"[^"]*"|'[^']*'))?\]|:not\((?:[a-zA-Z][\w-]*|#[\w-]+|\.[\w-]+|\[[\w-]+(?:[*^$]?=(?:"[^"]*"|'[^']*'))?\])\))+$/;

function matchSimple(el, sel) {
  if (!SIMPLE_RE.test(sel)) throw new Error(`test-dom: unsupported selector fragment: ${sel}`);
  const parts = sel.match(/:not\([^)]*\)|\[[^\]]*\]|[.#]?[\w-]+/g) || [];
  for (const part of parts) {
    if (part.startsWith(':not(')) {
      if (matchSimple(el, part.slice(5, -1))) return false;
    } else if (part.startsWith('#')) {
      if (el.getAttribute('id') !== part.slice(1)) return false;
    } else if (part.startsWith('.')) {
      if (!el.classList.contains(part.slice(1))) return false;
    } else if (part.startsWith('[')) {
      const m = part.slice(1, -1).match(/^([\w-]+)(?:([*^$]?)=(?:"([^"]*)"|'([^']*)'))?$/);
      if (!m) throw new Error(`test-dom: unsupported attribute selector: ${part}`);
      const have = el.getAttribute(m[1]);
      if (have === null) return false;
      if (m[2] === undefined && m[3] === undefined && m[4] === undefined) continue;
      const want = m[3] !== undefined ? m[3] : m[4];
      if (m[2] === '*') { if (!have.includes(want)) return false; }
      else if (m[2] === '^') { if (!have.startsWith(want)) return false; }
      else if (m[2] === '$') { if (!have.endsWith(want)) return false; }
      else if (have !== want) return false;
    } else if (el.localName !== part.toLowerCase()) return false;
  }
  return true;
}

function matchesOne(el, sel) {
  const steps = sel.trim().split(/\s+/);
  // Validate EVERY step before matching anything. Validating lazily would let an
  // unsupported combinator (`div > span`) pass silently whenever the last step happens not
  // to match — the exact way a fixture could look green while testing nothing.
  for (const step of steps) {
    if (!SIMPLE_RE.test(step)) throw new Error(`test-dom: unsupported selector fragment: ${step}`);
  }
  if (!matchSimple(el, steps[steps.length - 1])) return false;
  let node = el.parentNode;
  for (let i = steps.length - 2; i >= 0; i--) {
    let found = false;
    while (node && node.nodeType === 1) {
      if (matchSimple(node, steps[i])) { found = true; node = node.parentNode; break; }
      node = node.parentNode;
    }
    if (!found) return false;
  }
  return true;
}

function matchesAny(el, sel) {
  return String(sel).split(',').map(s => s.trim()).filter(Boolean).some(s => matchesOne(el, s));
}

// ── parser ───────────────────────────────────────────────────────────────────
function parseFragment(html, context = 'div') {
  const root = new Element(context);
  let cur = root;
  let i = 0;
  const s = String(html);
  while (i < s.length) {
    if (s.startsWith('<!--', i)) {
      const end = s.indexOf('-->', i);
      const stop = end === -1 ? s.length : end;
      cur.appendChild(new CommentNode(s.slice(i + 4, stop)));
      i = end === -1 ? s.length : end + 3;
      continue;
    }
    if (s.startsWith('</', i)) {
      const end = s.indexOf('>', i);
      const name = s.slice(i + 2, end === -1 ? s.length : end).trim().toLowerCase();
      let n = cur;
      while (n !== root && n.localName !== name) n = n.parentNode;
      if (n !== root) cur = n.parentNode || root;
      i = end === -1 ? s.length : end + 1;
      continue;
    }
    if (s[i] === '<' && /[a-zA-Z]/.test(s[i + 1] || '')) {
      const end = findTagEnd(s, i);
      const raw = s.slice(i + 1, end);
      const selfClosing = raw.endsWith('/');
      const m = raw.match(/^([\w:-]+)/);
      const el = new Element(m[1]);
      for (const a of raw.slice(m[1].length).matchAll(/([\w:.@-]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+)))?/g)) {
        el.attrs.set(a[1].toLowerCase(), unescape(a[2] !== undefined ? a[2] : a[3] !== undefined ? a[3] : a[4] !== undefined ? a[4] : ''));
      }
      cur.appendChild(el);
      i = end + 1;
      if (VOID.has(el.localName) || selfClosing) continue;
      if (RAW.has(el.localName)) {
        const close = s.toLowerCase().indexOf('</' + el.localName, i);
        const stop = close === -1 ? s.length : close;
        if (stop > i) el.appendChild(new TextNode(s.slice(i, stop)));
        i = close === -1 ? s.length : s.indexOf('>', close) + 1;
        continue;
      }
      cur = el;
      continue;
    }
    const next = s.indexOf('<', i);
    const stop = next === -1 ? s.length : next;
    cur.appendChild(new TextNode(unescape(s.slice(i, stop))));
    i = stop;
  }
  const kids = root.childNodes.slice();
  for (const k of kids) k.parentNode = null;
  root.childNodes.length = 0;
  return kids;
}

/** Tag end that tolerates a `>` inside a quoted attribute value. */
function findTagEnd(s, start) {
  let q = '';
  for (let i = start + 1; i < s.length; i++) {
    const c = s[i];
    if (q) { if (c === q) q = ''; continue; }
    if (c === '"' || c === "'") { q = c; continue; }
    if (c === '>') return i;
  }
  return s.length;
}

class Doc extends Element {
  constructor(html, { lang = 'en' } = {}) {
    super('html');
    this.setAttribute('lang', lang);
    this.documentElement = this;
    this.body = new Element('body');
    this.appendChild(this.body);
    this.body.innerHTML = html;
  }
  createElement(tag) { return new Element(tag); }
  createTextNode(t) { return new TextNode(t); }
  getElementById(id) { return this.querySelector(`[id="${id}"]`); }
  get innerHTMLOfBody() { return this.body.innerHTML; }
}

/** Build a document from a markup fragment. */
export function makeDocument(html, opts) {
  return new Doc(html, opts);
}

/** Parse/serialize fidelity gate: the shim must round-trip the exact bytes it was given,
 *  so a fixture cannot pass against a tree the parser got wrong. */
export function assertParses(assert, html, label) {
  const doc = makeDocument(html);
  assert(doc.body.innerHTML === html, `test-dom round-trips ${label} byte for byte`);
  return doc;
}

export function testDomDemo(assert) {
  // Round-trip fidelity, including the constructs the offer region actually uses.
  for (const [html, label] of [
    ['<div class="a b" data-offer="title">x</div>', 'attributes + text'],
    ['<a class="btn" data-offer="cta" href="#" hidden>Go</a>', 'a bare boolean attribute'],
    ['<img data-offer="image" class="i" alt="" hidden>', 'a void element'],
    ['<!--OFFER:START-->\n<p>a</p>\n<!--OFFER:END-->', 'comments and newlines between nodes'],
    ['<div title="a &gt; b">x &amp; y</div>', 'escaped attribute and text'],
    ['<div class="wysiwyg"><p>Get up to <strong>$10,000</strong></p></div>', 'nested rich text'],
    ['<div style="top:2.5rem">x</div>', 'a style attribute'],
  ]) assertParses(assert, html, label);

  const doc = makeDocument('<section><div id="t" class="a" data-offer="title">Old</div><a data-offer="cta" href="#" hidden>Go</a></section>');
  const title = doc.querySelector('[data-offer="title"]');
  assert(title && title.textContent === 'Old', 'attribute selector finds the hook');
  title.textContent = 'New <b>';
  assert(title.outerHTML === '<div id="t" class="a" data-offer="title">New &lt;b&gt;</div>', 'textContent assignment ESCAPES');
  const cta = doc.querySelector('[data-offer="cta"]');
  assert(cta.hidden === true, 'the hidden property reads the attribute');
  cta.hidden = false;
  assert(cta.outerHTML === '<a data-offer="cta" href="#">Go</a>', 'clearing hidden removes the attribute from the markup');
  cta.hidden = true;
  assert(cta.outerHTML === '<a data-offer="cta" href="#" hidden>Go</a>', 'setting it back restores the bare form');

  // Removal has to be visible in the serialized parent — this is the assertion shape the
  // stale-DOM requirement needs.
  const rm = makeDocument('<div class="wrap"><span class="stale">x</span><span class="keep">y</span></div>');
  rm.querySelector('.stale').remove();
  assert(rm.body.innerHTML === '<div class="wrap"><span class="keep">y</span></div>', 'remove() deletes the node from the tree');

  // Selector coverage the islands rely on.
  const sel = makeDocument('<div id="available"><div class="row"><div class="col-12 col-md-6 mb-4"><div class="card spec-card" data-listing-id="a"><a href="/new-homes/tx/x/1/">l</a></div></div></div></div>');
  assert(sel.querySelector('#available .card.spec-card[data-listing-id]') !== null, 'descendant + compound selector');
  assert(sel.querySelectorAll('[data-listing-id]').length === 1, 'querySelectorAll');
  const card = sel.querySelector('.card.spec-card');
  assert(card.closest('.col-12.col-md-6') !== null, 'closest walks ancestors');
  assert(card.matches('.card:not(.other)') && !card.matches('.card:not(.spec-card)'), ':not()');
  assert(sel.querySelector('a[href*="/new-homes/tx/"]') !== null, 'attribute-contains selector');
  let threw = false;
  try { sel.querySelector('div > span'); } catch { threw = true; }
  assert(threw, 'an unsupported selector THROWS instead of silently matching nothing');

  // cloneNode(true) is how the islands stamp cards from a template column.
  const tpl = makeDocument('<div class="col"><span class="x">1</span></div>').querySelector('.col');
  const copy = tpl.cloneNode(true);
  copy.querySelector('.x').textContent = '2';
  assert(tpl.querySelector('.x').textContent === '1' && copy.querySelector('.x').textContent === '2', 'cloneNode(true) is a deep copy');
  const st = makeDocument('<div class="b">x</div>').querySelector('.b');
  st.style.top = '2.5rem';
  assert(st.outerHTML === '<div class="b" style="top:2.5rem">x</div>', 'style writes through to the attribute');
  console.log('test-dom.mjs demo() passed');
}

if (process.argv[1]?.endsWith('test-dom.mjs') && process.argv.includes('--check')) {
  testDomDemo((cond, msg) => { if (!cond) throw new Error('assertion failed: ' + msg); });
}
